# Rubrics {#rubrics}

#### Experimental design assessment framework {-} 
There are at least two primary modes of assessment. Formative assessment can happen during the learning process. This active process of engagement with content and doing experiments is critical to becoming an effective life-long learner and successful scientist. In practicing experimental design and doing experiments professionally, this can take the of form of notes, sketches, photographs of the process or experiment at different steps, flowcharts, field and lab notebooks, code, and discussion with collaborators. This process of learning can include feedback from the team (in this course the teaching assistant, the instructor, or peers examining the same challenge). It can be enabled by testing how well one has advanced in achieving specific outcomes. For instance, share your meta-data with a peer and explore whether the individual can understand the meaning of the data and the process of experimentation that supported the collection or reuse of data. Summative assessment can happen at the end of key benchmarks in a learning cycle or at the completion of logical stopping points within the learning process that generated concrete products for review and grading. In this designcraft process of actively exploring experimental design, this can include production of data with meta-data, a lab report describing the deeper dive for one of the field experiments, and a lab report describing the design process of data reuse from one the examples provided.  

A rubric is a scoring tool that enables fair, transparent and replicable grading in summative evaluation. Checklists are useful for formative self or peer assessment in the steps along the way to final products. In designcraft for experiments, this applies to the published data with meta-data and lab reports. In the formal offering of these labs for the course 'SC/BIOL 3250 4.00 Experimental design for environmental and evolutionary biology' at York University, the lab component is worth 50% of the final grade.

#### Lab component weightings {-}  
Dataset with meta-data for pilot experiment 5%  
Dataset with meta-data for field experiment 5%  
Field lab report 30%  
Data-design lab report 10%  

#### Specific rubrics {-}  

**Pilot experiment data with meta-data**  
1. Select one of the first three field experiments.   
2. Publish your data with meta-data to an open and public data repository such as [figshare](https://figshare.com).  
3. Share the link with all the files with the teaching assistment via the course turnitin.com platform.  






